### ISSUE TITLE
It only put my monitor on 100% of brightness, but no more changes

### ISSUE THREAD

**Issue by patoroco** [superduper/BrightnessMenulet#1]
Hi,
I've a Dell U2410 and I would like to use this app for it. The problem is that when I move the % on the menulet, the brigthness of my screen go to 100% and never change to other values. I'm trying using a DVI cable with original converter from mini-DP --> DVI.

If I could help you in the development with any logs, tell me and I try to do it with XCode (I'm iOS developer).

Cheers!

**Comment by dentarg** [comment]
@superduper I believe this issue was accidentally closed by the big merge (#56)
