### ISSUE TITLE
Still working on keyboard shortcuts?

### ISSUE THREAD

**Issue by jns1986** [superduper/BrightnessMenulet#2]
Great app! works just fine on my Dell S2340L.
Would really love keyboard shortcuts to make my "mac" a little more mac-like..!

**Comment by dipovespo** [comment]
+1. Maybe it could have been set to adjust all monitor or each monitor (e.g external monitor with cmd + F1/F2). Btw works fine on Dell U2715H, thank you.

**Comment by ananggadipa** [comment]
Is keyboard shortcut has been implemented? Couldn't find the settings.
